### ISSUE TITLE
search route doesent work

### ISSUE THREAD

**Issue by bqstony** [idoop/docker-nuget-server#1]
change route to: 
rewrite ^/search/$ /search.php;

then it would be accesable with http://localhost/search/

https://github.com/idoop/docker-nuget-server/blob/1a62425475663b82ac977dd1a1e9a69859dc0ec0/nginx.conf.example#L17

**Comment by idoop** [comment]
@bqstony 
There is no better solution to this bug in docker container.
Please add env  `SERVER_NAME` value, eg `-e SERVER_NAME="nuget.yourDomain.com"` or you machine IP (not container ip) + port :`-e SERVER_NAME="192.168.xx.xx:8080"`, this maybe helpful.
