### ISSUE TITLE
Attempts to download the nupkg have failed

### ISSUE THREAD

**Issue by ajamrozek** [idoop/docker-nuget-server#4]
I was able to install this into my k8s environment and ultimately pushed some nupkg files to it. Calling the V2 api I'm able to list all the packages also. The problem occurs when I try to install these packages. 
My Visual Studio 2017 reads them in Package Manager and it seem slike they're installable but I encounter this error:
**The feed 'Scenario Manager Common [http://sm-dev.kubeodc.corp.intranet/nuget]' lists package 'ScenarioManager.Common.Utilities.1.0.0.48946' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again.**
![NuGetErr](https://user-images.githubusercontent.com/1176126/54869882-4ae37600-4d64-11e9-96a2-d90ea271375e.PNG)

**Comment by idoop** [comment]
Have you prepared a persistent storage solution for this nuget server in Kubernetes? Like `PVC`?
Please check that the volume folders contains the files you uploaded.

**Comment by ajamrozek** [comment]
Ah, I'll work with my admin to see about PVC on my pod. I do see the files in the pod though.

**Comment by idoop** [comment]
In my test, It's work and everythin is Ok.
@ajamrozek Can show your kube yaml file's content?

**Comment by ajamrozek** [comment]
The PVC issue is likely the problem. My k8s admin isn't going to add persistent volumes so I have to abandon this solution. However, we have a NuGet server I just learned of, so I don't need a docker image after all. 
Thanks for responding though.

**Comment by liang1224** [comment]
ajamrozek: 
你好!
我也遇到了这个问题, 看到了你的评论:

> Have you prepared a persistent storage solution for this nuget server in Kubernetes? Like PVC?
> Please check that the volume folders contains the files you uploaded.

但是我没有明白这是什么意思. 我尝试修改了一些 nuget.conf的配置, 并将SERVER_NAME设置为我机器的ip地址,但是没有生效.
希望得到你的回应.

Google Translate:
Ajamrozek:
Hello there!
I also encountered this problem and saw your comment:

> Have you prepared a persistent storage solution for this nuget server in Kubernetes? Like PVC?
> Please check that the volume folders contains the files you uploaded.

But I don't understand what this means. I tried to modify some of the nuget.conf configuration and set SERVER_NAME to the ip address of my machine, but it didn't take effect.
I hope to get your response.

**Comment by idoop** [comment]
@liang1224 能详细的吗?比如运行环境/错误提示/配置等..或者直接贴一下你的kube yaml文件?或这直接[email](mailto://idoop@msn.cn)我.
每个人的运行环境都不同,只描述现象是没办法解决的.

**Comment by lljxww** [comment]
> @liang1224 能详细的吗?比如运行环境/错误提示/配置等..或者直接贴一下你的kube yaml文件?或这直接[email](mailto://idoop@msn.cn)我.
> 每个人的运行环境都不同,只描述现象是没办法解决的.

谢谢! 我已经解决了这个问题.
