### ISSUE TITLE
Permission in External Volumes

### ISSUE THREAD

**Issue by nelfer** [idoop/docker-nuget-server#5]
Hi,

When mounting volumes like [My/path]:[/var/www/something] the application crashes. After investigating for a good while, it is because it fails to create the database. What I notice is that when I run it without mounting external volumes, the "/var/www/something" folder has owner and group www-data but when mounting, it is root.

If I run docker exec bash and modify permissions, then the app is able to create the database.

**Comment by idoop** [comment]
@nelfer Because `php-fpm` process is run as `www-data` user and group permission.
If use `docker-compose` ,the yaml file just like this:
``` yaml
...
  volumes:
  - /some/path/db:/var/www/simple-nuget-server/db:Z
  - /some/path/pkgs:/var/www/simple-nuget-server/packagefiles:Z
...
```

**Comment by nelfer** [comment]
OK thanks
Should that be documented in the README.md?

I noticed that's a Linux modifier. Would there be a general solution for all OSes? Or it just so happen to be an issue in Linux only?

**Comment by idoop** [comment]
It's also vaild for other x86_64 platforms(like MacOS,BSD),Only Windows platform dose not work.
