### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by iwaitu** [idoop/docker-nuget-server#6]
> 019/09/11 02:59:59 [error] 34#34: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/simple-nuget-server/inc/db.php:10
Stack trace:
#0 /var/www/simple-nuget-server/inc/db.php(10): PDO->__construct('sqlite:../db/pa...', NULL, NULL)
#1 /var/www/simple-nuget-server/inc/db.php(386): DB::init()
#2 /var/www/simple-nuget-server/inc/core.php(3): require('/var/www/simple...')
#3 /var/www/simple-nuget-server/public/index.php(2): require('/var/www/simple...')
#4 {main}
  thrown in /var/www/simple-nuget-server/inc/db.php on line 10" while reading response header from upstream, client: 192.168.0.121, server: nuget.ivilson.com:80, request: "PUT /api/v2/package/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "nuget.ivilson.com"
192.168.0.121 - - [11/Sep/2019:02:59:59 +0000] "PUT /api/v2/package/ HTTP/1.1" 500 5 "-" "NuGet Command Line/5.2.0 (Microsoft Windows NT 6.2.9200.0)" "220.173.39.41"
2019/09/11 02:59:59 [error] 34#34: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/simple-nuget-server/inc/db.php:10
Stack trace:
#0 /var/www/simple-nuget-server/inc/db.php(10): PDO->__construct('sqlite:../db/pa...', NULL, NULL)
#1 /var/www/simple-nuget-server/inc/db.php(386): DB::init()
#2 /var/www/simple-nuget-server/inc/core.php(3): require('/var/www/simple...')
#3 /var/www/simple-nuget-server/public/index.php(2): require('/var/www/simple...')
#4 {main}
  thrown in /var/www/simple-nuget-server/inc/db.php on line 10" while reading response header from upstream, client: 192.168.0.121, server: nuget.ivilson.com:80, request: "PUT /api/v2/package/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "nuget.ivilson.com"
192.168.0.121 - - [11/Sep/2019:02:59:59 +0000] "PUT /api/v2/package/ HTTP/1.1" 500 5 "-" "NuGet Command Line/5.2.0 (Microsoft Windows NT 6.2.9200.0)" "220.173.39.41"
2019/09/11 03:00:00 [error] 34#34: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/simple-nuget-server/inc/db.php:10
Stack trace:
#0 /var/www/simple-nuget-server/inc/db.php(10): PDO->__construct('sqlite:../db/pa...', NULL, NULL)
#1 /var/www/simple-nuget-server/inc/db.php(386): DB::init()
#2 /var/www/simple-nuget-server/inc/core.php(3): require('/var/www/simple...')
#3 /var/www/simple-nuget-server/public/index.php(2): require('/var/www/simple...')
#4 {main}
  thrown in /var/www/simple-nuget-server/inc/db.php on line 10" while reading response header from upstream, client: 192.168.0.121, server: nuget.ivilson.com:80, request: "PUT /api/v2/package/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "nuget.ivilson.com"
192.168.0.121 - - [11/Sep/2019:03:00:00 +0000] "PUT /api/v2/package/ HTTP/1.1" 500 5 "-" "NuGet Command Line/5.2.0 (Microsoft Windows NT 6.2.9200.0)" "220.173.39.41"

**Comment by iwaitu** [comment]
I deploy this dock image on ubuntu by rancher2.

**Comment by idoop** [comment]
@iwaitu   Can show your docker-compose.yaml file or docker run command ?

**Comment by idoop** [comment]
Now can use [`BASE_URL`](https://github.com/idoop/docker-nuget-server#environment-configuration) env for forward  reverse proxy.

**Comment by beslst** [comment]
I know it is a bit late, but for future reference, you have to run
```
chmod 33:33 ./nuget-packages
chmod 33:33 ./nuget-db
```
so that the nginx user can access the folders
