### ISSUE TITLE
bug in entrypoint - SERVER_PORT

### ISSUE THREAD

**Issue by Steinblock** [idoop/docker-nuget-server#9]
If you set the SERVER_PORT env value the following script will be executed in https://github.com/idoop/docker-nuget-server/blob/master/docker-entrypoint

```
    sed -i -e "s/listen 80/listen ${SERVER_PORT}/" /etc/nginx/conf.d/nuget.conf
```

I set `SERVER_PORT` to 8080 and restarted the container. The nuget server listened on port 8080 as expected.

I set `SERVER_PORT` back to 80 and restarted the container. The nuget server still listened on port 8080 and was not reachable anymore.

**Comment by blindzero** [comment]
I have the issue other way around:
I set SERVER_NAME: "localhost:8080" and SERVER_PORT: "8080" and it is still trying to bind to 80
